apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (include "reposilite.deployment.annotations" . | fromYaml) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (include "reposilite.deployment.labels" . | fromYaml) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "reposilite.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "reposilite.pod.selectorLabels" . | nindent 6 }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with (include "reposilite.pod.annotations" . | fromYaml) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reposilite.pod.labels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - {{- if gt (len .Values.deployment.reposilite.args) 0 }}
        args:
        {{- range .Values.deployment.reposilite.args }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if gt (len .Values.deployment.reposilite.command) 0 }}
        command:
        {{- range .Values.deployment.reposilite.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- with .Values.deployment.reposilite.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.reposilite.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ include "reposilite.deployment.images.reposilite.fqin" . | quote }}
        imagePullPolicy: {{ .Values.deployment.reposilite.image.pullPolicy }}
        livenessProbe:
          tcpSocket:
            port: http
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        name: reposilite
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: http
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 3
        {{- with .Values.deployment.reposilite.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.reposilite.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- $volumeMounts := (include "reposilite.deployment.reposilite.volumeMounts" . | fromYaml) }}
        {{- if and (hasKey $volumeMounts "volumeMounts") (gt (len $volumeMounts.volumeMounts) 0) }}
        volumeMounts:
        {{- toYaml $volumeMounts.volumeMounts | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.dnsPolicy }}
      dnsPolicy: {{ .Values.deployment.dnsPolicy }}
      {{- end }}
      {{- if .Values.deployment.hostname }}
      hostname: {{ .Values.deployment.hostname }}
      {{- end }}
      hostNetwork: {{ .Values.deployment.hostNetwork }}
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.priorityClassName }}
      priorityClassName: {{ .Values.deployment.priorityClassName }}
      {{- end }}
      {{- if .Values.deployment.restartPolicy }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      {{- end }}
      {{- with .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ include "reposilite.deployment.serviceAccount" . }}
      {{- if .Values.deployment.subdomain }}
      subdomain: {{ .Values.deployment.subdomain }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- $volumes := (include "reposilite.deployment.volumes" . | fromYaml) }}
      {{- if and (hasKey $volumes "volumes") (gt (len $volumes.volumes) 0) }}
      volumes:
      {{- toYaml $volumes.volumes | nindent 6 }}
      {{- end }}