apiVersion: v1
kind: Service
metadata:
  name: {{ include "reposilite.fullname" . }}
  annotations:
  {{- with .Values.service.annotations  }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "reposilite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reposilite.selectorLabels" . | nindent 4 }}
