# GitHub Actions workflow to automatically deploy the helm chart(s).
name: "Helm"
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "charts/**" ]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Configure Git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: "Install Helm"
        uses: azure/setup-helm@v3
        with:
          version: v3.10.1

      - name: "Release"
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_repo_url: https://helm.reposilite.com
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"