name: Markdown linter

on:
  pull_request:
    paths: [ "**/*.md" ]
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches:
    - '**'
    paths: [ "**/*.md" ]
    tags-ignore:
    - '**'
  workflow_dispatch: {}

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: '**/*.md'